<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1FVTVBj\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1FVTVBj/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1FVTVBj.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1FVTVBj\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container1FVTVBj\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => '1FVTVBj',
    'container.build_id' => '6e35ebd0',
    'container.build_time' => 1544108259,
), __DIR__.\DIRECTORY_SEPARATOR.'Container1FVTVBj');
